vpx set dofile abort exit
vpx set screen display -noprogress
tclmode

# Generated by Genus(TM) Synthesis Solution 17.21-s010_1, revision 1.257c
# Generated on: Sat Dec 30 13:28:10 IST 2023 (Sat Dec 30 07:58:10 GMT 2023)

tcl_set_command_name_echo on

set_log_file logs/intermediate2final.lec.log -replace

usage -auto -elapse

set_verification_information fv_map_aes_cipher_top_mv_db

read_implementation_information fv/aes_cipher_top -golden fv_map -revised aes_cipher_top_mv

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license

set env(RC_VERSION)     "17.21-s010_1"
set env(CDN_SYNTH_ROOT) "/home/install/GENUS172/tools.lnx86"
set CDN_SYNTH_ROOT      "/home/install/GENUS172/tools.lnx86"
set env(CW_DIR) "/home/install/GENUS172/tools.lnx86/lib/chipware"
set CW_DIR      "/home/install/GENUS172/tools.lnx86/lib/chipware"

set_lowpower_option -native_1801

set_lowpower_option -native_1801
set_lowpower_option -revised_analysis_style  post_synthesis

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path . -library -both
read_library -liberty -both -lp  /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM2_4096X32_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM2_2048X32_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/pdkIO.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM2_512X32_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM2_136X32_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM2_128X16_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM2_1024X32_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM1_4096X32_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM1_256X32_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM1_1024X32_slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/slow.lib /home/vlsi1/pdTraining/synthesis/../technology/45/lib/max/MEM2_128X32_slow.lib

read_design -verilog95   -golden -lastmod -noelab fv/aes_cipher_top/fv_map.v.gz
elaborate_design -golden -root {aes_cipher_top}

read_design -verilog95   -revised -lastmod -noelab outputs/aes_cipher_top_m.v
elaborate_design -revised -root {aes_cipher_top}

read_power_intent  -1801 -golden fv/aes_cipher_top/fv_map.upf

#add_name_alias fv/aes_cipher_top/fv_map.singlebit.original_name.alias.json.gz -golden
#set_mapping_method -alias -golden

read_power_intent  -1801 -revised ../scripts/genus/block.upf

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/aes_cipher_top/aes_cipher_top_mv.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff -both

set_analyze_option -auto

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -extra -unreachable -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

tclmode
puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}
vpxmode
exit -f
